package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new xyz.bczl.flutter.easy_permission.FlutterEasyPermissionPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin flutter_easy_permission, xyz.bczl.flutter.easy_permission.FlutterEasyPermissionPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.legendsec.flutter_scankit_plus.FlutterScankitPlusPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin flutter_scankit_plus, com.legendsec.flutter_scankit_plus.FlutterScankitPlusPlugin", e);
    }
  }
}
